"""The storage contract shared by the Mongo and in-memory backends."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Protocol, runtime_checkable

Doc = dict[str, Any]


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def as_utc(value: Any) -> Any:
    """BSON dates come back naive; re-attach UTC so comparisons are safe."""
    if isinstance(value, datetime) and value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value


@runtime_checkable
class Store(Protocol):
    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...
    async def ping(self) -> bool: ...

    # ---- lines ----
    async def create_line(
        self, twilio_number: str, label: str, active: bool = True
    ) -> Doc: ...
    async def list_lines(self, active_only: bool = True) -> list[Doc]: ...
    async def get_line(self, line_id: str) -> Doc | None: ...
    async def get_line_by_number(self, twilio_number: str) -> Doc | None: ...
    async def update_line(self, line_id: str, **fields: Any) -> Doc | None: ...

    # ---- threads ----
    async def create_thread(
        self,
        line_id: str,
        counterpart_number: str,
        counterpart_label: str | None = None,
    ) -> Doc: ...
    async def find_thread(
        self, line_id: str, counterpart_number: str
    ) -> Doc | None: ...
    async def get_thread(self, thread_id: str) -> Doc | None: ...
    async def list_threads(self, line_ids: list[str] | None = None) -> list[Doc]: ...
    async def update_thread(self, thread_id: str, **fields: Any) -> Doc | None: ...
    async def bump_thread(
        self,
        thread_id: str,
        last_message_at: datetime,
        preview: str,
        direction: str,
        unread_delta: int = 0,
        has_media: bool = False,
    ) -> None: ...
    async def clear_unread(self, thread_id: str) -> Doc | None: ...
    async def delete_thread(self, thread_id: str) -> int: ...

    # ---- messages ----
    async def insert_message(self, doc: Doc) -> Doc: ...
    async def list_messages(
        self, thread_id: str, after: datetime | None = None, limit: int = 250
    ) -> list[Doc]: ...
    async def get_message(self, message_id: str) -> Doc | None: ...
    async def find_message_by_sid(self, twilio_sid: str) -> Doc | None: ...
    async def update_message(self, message_id: str, **fields: Any) -> Doc | None: ...
    async def update_message_by_sid(
        self, twilio_sid: str, **fields: Any
    ) -> Doc | None: ...
    async def patch_media(
        self, message_id: str, index: int, patch: Doc
    ) -> Doc | None: ...
    async def find_by_media_token(self, token: str) -> tuple[Doc, int] | None: ...
